package fifi;

import java.io.IOException;
import java.time.DateTimeException;

import fifi.command.Command;
import fifi.exception.FifiException;

/**
 * Entry point for the Fifi chatbot application.
 */
public class Fifi {
    private final Storage storage;
    private final TaskList tasks;
    private final Ui ui;
    private boolean isExit;

    /**
     * Creates a chatbot that stores tasks at the given file path.
     *
     * @param filePath the path of the task data file
     */
    public Fifi(String filePath) {
        ui = new Ui();
        storage = new Storage(filePath);
        tasks = loadTasks();
        isExit = false;
    }

    /**
     * Starts reading and executing user commands.
     */
    public void run() {
        ui.showWelcome();
        while (!isExit) {
            try {
                String input = ui.readCommand();
                Command command = Parser.parse(input);
                command.execute(tasks, ui, storage);
                isExit = command.isExit();
            } catch (FifiException e) {
                ui.showResponse(e.getMessage());
            } catch (IOException e) {
                ui.showResponse("Oops! I could not save your tasks to the hard disk.");
            } catch (DateTimeException e) {
                ui.showResponse("Oops! Please use yyyy-MM-dd for dates.");
            } catch (IndexOutOfBoundsException e) {
                ui.showResponse(getTaskNumberError());
            }
        }
    }

    /**
     * Returns Fifi's response to one user command.
     *
     * @param input the full command typed by the user
     * @return the response generated by Fifi
     */
    public String getResponse(String input) {
        return getChatResponse(input).getMessage();
    }

    /**
     * Returns a response whose error status lets the GUI choose its appearance.
     *
     * @param input the full command typed by the user
     * @return the response message and whether the command failed
     */
    public ChatResponse getChatResponse(String input) {
        ResponseUi responseUi = new ResponseUi();
        try {
            Command command = Parser.parse(input);
            command.execute(tasks, responseUi, storage);
            isExit = command.isExit();
        } catch (FifiException e) {
            responseUi.showError(e.getMessage());
        } catch (IOException e) {
            responseUi.showError("Oops! I could not save your tasks to the hard disk.");
        } catch (DateTimeException e) {
            responseUi.showError("Oops! Please use yyyy-MM-dd for dates.");
        } catch (IndexOutOfBoundsException e) {
            responseUi.showError(getTaskNumberError());
        }
        return responseUi.getResponse();
    }

    /**
     * Returns whether Fifi has received the exit command.
     *
     * @return true if Fifi should stop accepting commands
     */
    public boolean isExit() {
        return isExit;
    }

    /**
     * Starts Fifi using the default task data file.
     *
     * @param args command line arguments supplied by Java
     */
    public static void main(String[] args) {
        new Fifi("data/duke.txt").run();
    }

    /**
     * Returns task-number guidance that also handles an empty task list.
     */
    private String getTaskNumberError() {
        if (tasks.size() == 0) {
            return "Oops! Your task list is empty. Add a task first.";
        }
        return "Oops! Please enter a task number between 1 and " + tasks.size() + ".";
    }

    private TaskList loadTasks() {
        try {
            return new TaskList(storage.loadTasks());
        } catch (IOException e) {
            return new TaskList();
        }
    }

    /**
     * Captures command responses for GUI use instead of printing them to the console.
     */
    private static class ResponseUi extends Ui {
        private ChatResponse response = new ChatResponse("", false);

        @Override
        public void showResponse(String... messages) {
            response = new ChatResponse(String.join(System.lineSeparator(), messages), false);
        }

        @Override
        public void showError(String message) {
            response = new ChatResponse(message, true);
        }

        private ChatResponse getResponse() {
            return response;
        }
    }
}
