package fifi;

import java.io.IOException;
import java.time.DateTimeException;

import fifi.command.Command;
import fifi.exception.FifiException;

/**
 * Entry point for the Fifi chatbot application.
 */
public class Fifi {
    private final Storage storage;
    private final TaskList tasks;
    private final Ui ui;
    private boolean isExit;

    /**
     * Creates a chatbot that stores tasks at the given file path.
     *
     * @param filePath the path of the task data file
     */
    public Fifi(String filePath) {
        ui = new Ui();
        storage = new Storage(filePath);
        tasks = loadTasks();
        isExit = false;
    }

    /**
     * Starts reading and executing user commands.
     */
    public void run() {
        ui.showWelcome();
        while (!isExit) {
            try {
                String input = ui.readCommand();
                Command command = Parser.parse(input);
                command.execute(tasks, ui, storage);
                isExit = command.isExit();
            } catch (FifiException e) {
                ui.showResponse(e.getMessage());
            } catch (IOException e) {
                ui.showResponse("Oops! I could not save your tasks to the hard disk.");
            } catch (DateTimeException e) {
                ui.showResponse("Oops! Please use yyyy-MM-dd for dates.");
            }
        }
    }

    /**
     * Returns Fifi's response to one user command.
     *
     * @param input the full command typed by the user
     * @return the response generated by Fifi
     */
    public String getResponse(String input) {
        ResponseUi responseUi = new ResponseUi();
        try {
            Command command = Parser.parse(input);
            command.execute(tasks, responseUi, storage);
            isExit = command.isExit();
        } catch (FifiException e) {
            responseUi.showResponse(e.getMessage());
        } catch (IOException e) {
            responseUi.showResponse("Oops! I could not save your tasks to the hard disk.");
        } catch (DateTimeException e) {
            responseUi.showResponse("Oops! Please use yyyy-MM-dd for dates.");
        }
        return responseUi.getResponse();
    }

    /**
     * Returns whether Fifi has received the exit command.
     *
     * @return true if Fifi should stop accepting commands
     */
    public boolean isExit() {
        return isExit;
    }

    /**
     * Starts Fifi using the default task data file.
     *
     * @param args command line arguments supplied by Java
     */
    public static void main(String[] args) {
        new Fifi("data/duke.txt").run();
    }

    private TaskList loadTasks() {
        try {
            return new TaskList(storage.loadTasks());
        } catch (IOException e) {
            return new TaskList();
        }
    }

    /**
     * Captures command responses for GUI use instead of printing them to the console.
     */
    private static class ResponseUi extends Ui {
        private String response = "";

        @Override
        public void showResponse(String... messages) {
            response = String.join(System.lineSeparator(), messages);
        }

        private String getResponse() {
            return response;
        }
    }
}
